email: matti.luukkainen@helsinki.fi
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ohjelmistotekniikka-hy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mluukkai
repo_url: "https://github.com/ohjelmistotekniikka-hy/ohjelmistotekniikka-hy.github.io"
repo_branch: "master"

# Kurssikertaan liittyvät muuttujat:
title: Ohjelmistotekniikka, kevät 2021

# aikataulut (annetaan muodossa viikonpäivä dd.mm kellonaika)
wk1dl: "tiistai 23.03. klo 23:59"
wk2dl: "tiistai 30.03. klo 23:59"
wk3dl: "tiistai 06.04. klo 23:59"
wk4dl: "tiistai 13.04. klo 23:59"
wk5dl: "tiistai 20.04. klo 23:59"
wk6dl: "tiistai 27.04. klo 23:59"
finaldl: "sunnuntai 09.05. klo 23:59"
code_review_start_date: "keskiviikko 02.12. klo 23:59"

# aloitusluento muodossa viikonpäivä dd.mm kellonaika
# HUOM Kirjoita viikonpäivä isolla, sillä se tulee lauseen alkuun

# ohjausajat
# - ma 14-16  [zoom](https://helsinki.zoom.us/j/68570587158?pwd=TFhwUXBucExZeVNJZnRydE8yWkNFdz09)
# - ti 14-16  [zoom]() (alkaen 23.3.)
# - to 13-15  [zoom]()

times: 
  - time: "ma 14-16  [zoom](https://helsinki.zoom.us/j/68570587158?pwd=TFhwUXBucExZeVNJZnRydE8yWkNFdz09)"
  - time: "ti 14-16  [zoom]()"
  - time: "to 13-15  [zoom](https://helsinki.zoom.us/j/69701027000) (alkaen 25.3.)"

lecture: "Tiistai 16.03. klo 12-14"

# Linkki zoomiin tai youtubeen
lecture_link: "[tallenne](https://youtu.be/4RCyYKp1LAk)"

# seuraava kurssikerta muodossa syksyllä/keväällä [vuosi]. 
# esimerkki syksyllä 2021
# käytetään muun muassa "ei voi jatkaa seuraavalla kurssilla (syksyllä 2021)"
next_course: "syksyllä 2021"

labtool_link: "https://study.cs.helsinki.fi/labtool/courses/TKT20002.2021.K.K.1"

# referenssi-sovellusten linkit
python_reference_app_url: "https://github.com/ohjelmistotekniikka-hy/python-todo-app"
java_reference_app_url: "https://github.com/mluukkai/OtmTodoApp"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
